### ISSUE TITLE
Reorderable List causes replacement of values

### ISSUE THREAD

**Issue by RecoFloof** [orels1/UdonToolkit#36]
Steps to reproduce:

1. Create a program like this
```csharp
public class TestBug : UdonSharpBehaviour
{
    public string testString = "abc";
    public TestBug[] testArray;
}
```

2. Create 3 GameObjects with this program and assign unique `testString` values but don't assign anything in the `testArray` yet
3. Verify all have unique values in testString
4. Add element to `testArray` on the first object and reference it to the second object
5. Add element to `testArray` on the second object and reference it to the third object
6. Inspect the first object again
7. The second object is now replaced with the values of the third object

**Comment by MerlinVR** [comment]
This is a bug on U#'s side so I'll look at it now.

**Comment by RecoFloof** [comment]
Seems fixed in the latest U# master branch 👍
