### ISSUE TITLE
Using a custom label on a toggle attribute throws an error when doing a VRC build

### ISSUE THREAD

**Issue by Phasedragon** [orels1/UdonToolkit#47]
![image](https://user-images.githubusercontent.com/24859894/93074874-d415f900-f639-11ea-81e0-104270291ea0.png)

**Comment by orels1** [comment]
seems like i missed the 1 attribute constructor, should be a quick fix

**Comment by orels1** [comment]
Fixed on develop, here's the latest package for now

[UdonToolkit_v0.4.2.zip](https://github.com/orels1/UdonToolkit/files/5217832/UdonToolkit_v0.4.2.zip)
